name: "Create Release & Publish Package"

# Trigger on any commit to main
on:
    push:
        branches: [main]

env:
    NODE_VERSION: 14.x
    CACHE_NAME: ci

jobs:
    package:
        name: "Package & Push to GitHub Packages"
        runs-on: ubuntu-latest
        steps:
            - name: "Setup - Checkout"
              uses: actions/checkout@v2.3.4

            - name: "Setup - Use Node.js ${{ env.NODE_VERSION }}"
              uses: actions/setup-node@v2.1.5
              with:
                  node-version: ${{ env.NODE_VERSION }}
                  registry-url: 'https://npm.pkg.github.com'

            - name: "Cache node modules"
              uses: actions/cache@v2
              with:
                  path: ~/.npm
                  key: ${{ runner.os }}-node-modules-${{ env.CACHE_NAME }}-${{ hashFiles('**/package-lock.json') }}
                  restore-keys: |
                      ${{ runner.os }}-node-modules-${{ env.CACHE_NAME }}-
            - name: "Install packages"
              id: install_packages
              run: npm install -g webpack webpack-cli
              
            - name: "Install dependencies"
              id: install_deps
              run: npm ci
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.ORG_GITHUB_ACTIONS_TOKEN }}

            - name: "Publish"
              run: npm publish
              env:
                  NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}